name: Create Release
on:
  push:
    tags:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: "Determine tag"
        run: "echo \"RELEASE_TAG=${GITHUB_REF#refs/tags/}\" >> $GITHUB_ENV"

      - name: "Create release"
        uses: "actions/github-script@v6"
        with:
          github-token: "${{ secrets.MY_GITHUB_TOKEN }}"
          script: |
            try {
              const response = await github.rest.repos.createRelease({
                draft: false,
                generate_release_notes: true,
                name: process.env.RELEASE_TAG,
                owner: context.repo.owner,
                prerelease: false,
                repo: context.repo.repo,
                tag_name: process.env.RELEASE_TAG,
              });
            
              core.exportVariable('RELEASE_ID', response.data.id);
              core.exportVariable('RELEASE_UPLOAD_URL', response.data.upload_url);
            } catch (error) {
              core.setFailed(error.message);
            }

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build with SBT
        uses: actions/setup-scala@v1
        with:
          scala-version: 2.12.x
        env:
          SBT_OPTS: "-Xms2g -Xmx2g"
        run: |
          echo "SBT Version"
          sbt sbtVersion
          
          echo "Building Project"
          sbt clean compile assembly